[sc-11259] Adding service accounts and s3 bucket for task storage
funcx-faas/helm-chart pull request #47
Opened 2021-11-23 04:21 UTC by joshbryan-globus

This adds an S3 bucket to cloudformation for each environment and introduces an EKS service account that gives access to the appropriate bucket to forwarder, web service, and websocket service deployments.

2021-11-23 16:35 UTC, sirosen requested changes
I'd like to see three changes before we go forward with this. We can discuss doing some or all. To enumerate and clarify:

1. Don't use a fixed bucket name per environment
2. Declare the IAM policy for R/W on the bucket in the CFN stack with the bucket
3. Only give permissions for the IAM actions which we need, not `s3:*`

2021-11-23 16:35 UTC, sirosen commented on cloudformation/funcx.yml
> +      BucketName: !Sub 'funcx-${EnvName}-task-storage'
This makes the buckets fixed in name on a per-env basis. That's _okay_, but it would be better if we weren't vulnerable to issues if someone creates `s3://funcx-test-task-storage` in their account, and we later create an environment named `test`. S3 buckets are a global namespace, so this is a place where the CFN automatic name-munging is valuable.
(If this seems far-fetched, consider how this plays if someone wants to deploy the CFN stack in their dev account. I've made this mistake before, and it makes parallel development around CFN difficult.)

We could let CFN generate the names and produce them as outputs. Or we could tag the buckets with the environment and then do a tag search on S3 to find them. One requires read access to S3 to scan for buckets, and the other requires read access to CFN to pull an output -- neither seems better or worse to me, but I've done the S3 tag scanning before, so I have the relevant code handy, if that tips the scales. In the short term, we could literally just copy down the bucket names into configs, and switch to these "advanced" discovery techniques later.

In terms of handling this in the CFN config, we could set up per-environment managed IAM policies for the buckets with fixed names. Because the scope of IAM managed policy names is limited to the account, this is safe.

i.e. I'd suggest switching to
```yaml
  FuncXTaskStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: environment
          Value: !Ref EnvName
        - Key: bucket_type
          Value: task_storage
      LifecycleConfiguration:  # I know, not related, but trivial to just include this today
        Rules:
          - ExpirationInDays: 30
            Status: Enabled
```

with no name specified.

And then we can setup a policy in this same CFN stack with
```yaml
  FuncXTaskStorageBucketRWPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "CFN-managed policy for read/write on the task bucket"
      ManagedPolicyName: !Sub "funcx-${EnvName}-task-bucket-rw"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
              - "s3:ListObject"
            Resource: !Join ["/", [!GetAtt FuncXTaskStorageBucket.Arn, "*"]]
```

2021-11-23 16:35 UTC, sirosen commented on cloudformation/clusterconfig-prod.yml
> +            Action: s3:*
If we don't want to pursue my recommendation about changing where and how the policy is declared, I'd at least ask that we narrow these permissions to the ones that we'll need:
```
s3:PutObject
s3:GetObject
s3:ListObject
```

We shouldn't need more, and it's always much safer to be specific with IAM actions. AWS frequently adds new actions.

(This applies to the dev config as well, of course.)

2021-11-23 21:07 UTC, sirosen commented
Per our conversation, we're going to live with the fixed per-env bucket naming because of the way that eksctl and cfn are ordered, and the difficulty in disentangling them.

Aside: I did have the somewhat-funny idea of a new "funcx-pre-eksctl" stack, to put CFN on "both sides of eksctl". That raises obvious red flags. 😄

2021-11-29 18:28 UTC, sirosen commented
It looks like the S3 IAM policy was only updated in the dev config. It looks good to me there. As soon as the same change is applied on the prod config, I'll approve.

2021-11-29 19:11 UTC, joshbryan-globus commented
@sirosen Good catch, just pushed the update to prod.

2021-11-29 19:34 UTC, sirosen approved these changes

2021-11-29 19:34 UTC, merged